/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/footer/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/header/AppHeader.vue')['default']
    AppLogin: typeof import('./src/components/layout/auth/AppLogin.vue')['default']
    AppMenu: typeof import('./src/components/layout/sideBar/AppMenu.vue')['default']
    AppMenuList: typeof import('./src/components/layout/sideBar/AppMenuList.vue')['default']
    AppPlayList: typeof import('./src/components/layout/playList/AppPlayList.vue')['default']
    AppPlayListItem: typeof import('./src/components/layout/playList/AppPlayListItem.vue')['default']
    AppResgister: typeof import('./src/components/layout/auth/AppResgister.vue')['default']
    DarkMode: typeof import('./src/components/layout/header/DarkMode.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    MenuList: typeof import('./src/components/layout/sideBar/MenuList.vue')['default']
    MySwiper: typeof import('./src/components/common/MySwiper.vue')['default']
    MyTitle: typeof import('./src/components/common/MyTitle.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/PlayerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/footer/PlayerVolumeSlider.vue')['default']
    PlayListItem: typeof import('./src/components/layout/playList/PlayListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
}
